# netlify.toml (Simplified and Foolproof)

[build]
  # The directory where your serverless functions are located.
  # We will manually create this folder and put our handler inside.
  functions = "functions"

# This rule makes your API accessible at a clean URL.
# For example: your-site.netlify.app/users instead of /functions/api/users
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
